HARD_SKILLS_WHITELIST = {
    # Microsoft & Office Suite
    "excel",
    "microsoft excel",
    "ms excel",
    "word",
    "microsoft word",
    "ms word",
    "powerpoint",
    "visio",
    "microsoft visio",
    "project",
    "microsoft project",
    "ms project",
    "sharepoint",
    "teams",
    "microsoft teams",
    "outlook",
    "access",
    "ms access",
    "office 365",
    # IT, Software & Development
    "python",
    "java",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "ruby",
    "php",
    "go",
    "rust",
    "swift",
    "sql",
    "mysql",
    "postgresql",
    "oracle",
    "mongodb",
    "redis",
    "cassandra",
    "elasticsearch",
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jira",
    "confluence",
    "trello",
    "asana",
    "linux",
    "unix",
    "networks",
    "networking",
    "information technology",
    "databases",
    "database administration",
    "cybersecurity",
    "information security",
    "firewalls",
    "tcp/ip",
    "dns",
    "dhcp",
    "vpn",
    "react",
    "angular",
    "vue",
    "node.js",
    "django",
    "flask",
    "spring",
    "net",
    "api",
    "rest",
    "graphql",
    # Engineering, Manufacturing & Architecture
    "autocad",
    "cad",
    "solidworks",
    "revit",
    "matlab",
    "simulink",
    "ansys",
    "catia",
    "creo",
    "gis",
    "arcgis",
    "qgis",
    "plm",
    "scada",
    "plc",
    "hmi",
    "labview",
    "spice",
    "verilog",
    "vhdl",
    "electrical distribution",
    "electrical engineering",
    "mechanical engineering",
    "civil engineering",
    "chemical engineering",
    "industrial engineering",
    "aerospace engineering",
    "engineering standards",
    "drawings",
    "schematics",
    "blueprints",
    "drafting",
    "structural analysis",
    "finite element analysis",
    "hvac",
    "mep",
    "piping",
    "welding",
    "machining",
    "cnc",
    "3d printing",
    "manufacturing",
    "fabrication",
    "robotics",
    "automation",
    "sensors",
    "microcontrollers",
    "arduino",
    "raspberry pi",
    "pcb design",
    # Business, Finance & Accounting
    "sap",
    "salesforce",
    "oracle ebs",
    "workday",
    "netsuite",
    "quickbooks",
    "xero",
    "tableau",
    "power bi",
    "looker",
    "bloomberg",
    "reuters",
    "capitaliq",
    "factset",
    "financial modeling",
    "accounting",
    "bookkeeping",
    "tax preparation",
    "auditing",
    "gaap",
    "ifrs",
    "payroll",
    "invoicing",
    "budgeting",
    "forecasting",
    "erp",
    "crm",
    "hris",
    "ats",
    "supply chain management",
    "logistics",
    "procurement",
    "inventory management",
    "business analysis",
    "data analysis",
    "financial analysis",
    "risk management",
    "valuation",
    "m&a",
    # Marketing, Design & Content
    "adobe",
    "photoshop",
    "illustrator",
    "indesign",
    "premiere",
    "after effects",
    "xd",
    "figma",
    "sketch",
    "invision",
    "canva",
    "google analytics",
    "seo",
    "sem",
    "google ads",
    "facebook ads",
    "hubspot",
    "mailchimp",
    "marketo",
    "salesforce marketing cloud",
    "html",
    "css",
    "wordpress",
    "drupal",
    "magento",
    "shopify",
    "ui",
    "ux",
    "ui/ux",
    "wireframing",
    "prototyping",
    "typography",
    "color theory",
    "video editing",
    "content management systems",
    "cms",
    "copywriting",
    "graphic design",
    "web design",
    "a/b testing",
    # Medical, Healthcare & Sciences
    "cpr",
    "bls",
    "acls",
    "pals",
    "emr",
    "ehr",
    "epic",
    "cerner",
    "meditech",
    "phlebotomy",
    "iv administration",
    "vital signs",
    "patient assessment",
    "triage",
    "wound care",
    "medication administration",
    "ekg",
    "ecg",
    "radiography",
    "ultrasound",
    "mri",
    "ct",
    "medical billing",
    "medical coding",
    "icd-10",
    "cpt",
    "hipaa",
    "infection control",
    "sterilization",
    "surgical assistance",
    "anesthesia",
    "pharmacology",
    "chemistry",
    "biology",
    "microbiology",
    "genetics",
    "pcr",
    "chromatography",
    "spectroscopy",
    "cell culture",
    # Operations, Quality & Miscellaneous
    "six sigma",
    "lean",
    "kaizen",
    "5s",
    "tqm",
    "iso 9001",
    "quality control",
    "quality assurance",
    "project management",
    "agile",
    "scrum",
    "kanban",
    "waterfall",
    "scheduling",
    "primavera",
    "maintenance",
    "troubleshooting",
    "repair",
    "calibration",
    "testing",
    "inspection",
    "safety",
    "osha",
    "compliance",
    "regulatory compliance",
    "documentation",
    "technical writing",
    "data entry",
    "technical documentation",
    "documentation skills",
    "wms",
    "warehouse management",
    "forklift",
    "cdl",
    "routing",
    "dispatching",
    "inventory control",
    "shipping",
    "receiving",
    "material handling",
}
